export { default as facebook } from './facebook.png'
export { default as instagram } from './instagram.png'
export { default as tiktok } from './tiktok.png'
export { default as website } from './website.png'
export { default as youtube } from './youtube.png'