export { default as A } from './A.png'
export { default as B } from './B.png'
export { default as C } from './C.png'
export { default as D } from './D.png'
export { default as E } from './E.png'
export { default as F } from './F.png'
export { default as G } from './G.png'
export { default as H } from './H.png'
export { default as I } from './I.png'
export { default as J } from './J.png'
export { default as K } from './K.png'
export { default as L } from './L.png'
export { default as M } from './M.png'
export { default as N } from './N.png'
export { default as O } from './O.png'
export { default as P } from './P.png'
export { default as Q } from './Q.png'
export { default as R } from './R.png'
export { default as S } from './S.png'
export { default as T } from './T.png'
export { default as U } from './U.png'
export { default as V } from './V.png'
export { default as W } from './W.png'
export { default as X } from './X.png'
export { default as Y } from './Y.png'
export { default as Z } from './Z.png'

export { default as AS } from './AS.png'
export { default as AF } from './AF.png'
export { default as AX } from './AX.png'
export { default as AR } from './AR.png'
export { default as AJ } from './AJ.png'

export { default as AA } from './AA.png'
export { default as AAS } from './AAS.png'
export { default as AAF } from './AAF.png'
export { default as AAR } from './AAR.png'
export { default as AAX } from './AAX.png'
export { default as AAJ } from './AAJ.png'

export { default as AW } from './AW.png'
export { default as AWS } from './AWS.png'
export { default as AWF } from './AWF.png'
export { default as AWR } from './AWR.png'
export { default as AWX } from './AWX.png'
export { default as AWJ } from './AWJ.png'

export { default as ES } from './ES.png'
export { default as EF } from './EF.png'
export { default as ER } from './ER.png'
export { default as EX } from './EX.png'
export { default as EJ } from './EJ.png'

export { default as EE} from './EE.png'
export { default as EES } from './EES.png'
export { default as EEF } from './EEF.png'
export { default as EER } from './EER.png'
export { default as EEX } from './EEX.png'
export { default as EEJ } from './EEJ.png'

export { default as IS } from './IS.png'
export { default as IF } from './IF.png'
export { default as IR } from './IR.png'
export { default as IX } from './IX.png'
export { default as IJ } from './IJ.png'

export { default as OS } from './OS.png'
export { default as OF } from './OF.png'
export { default as OR } from './OR.png'
export { default as OX } from './OX.png'
export { default as OJ } from './OJ.png'

export { default as OO } from './OO.png'
export { default as OOF } from './OOF.png'
export { default as OOS } from './OOS.png'
export { default as OOR } from './OOR.png'
export { default as OOX } from './OOX.png'
export { default as OOJ } from './OOJ.png'

export { default as OW } from './OW.png'
export { default as OWF } from './OWF.png'
export { default as OWS } from './OWS.png'
export { default as OWR } from './OWR.png'
export { default as OWX } from './OWX.png'
export { default as OWJ } from './OWJ.png'

export { default as US } from './US.png'
export { default as UF } from './UF.png'
export { default as UR } from './UR.png'
export { default as UX } from './UX.png'
export { default as UJ } from './UJ.png'

export { default as UW } from './UW.png'
export { default as UWS } from './UWS.png'
export { default as UWF } from './UWF.png'
export { default as UWR } from './UWR.png'
export { default as UWX } from './UWX.png'
export { default as UWJ } from './UWJ.png'

export { default as YS } from './YS.png'
export { default as YR } from './YR.png'
export { default as YF } from './YF.png'
export { default as YX } from './YX.png'
export { default as YJ } from './YJ.png'

// export { default as } from './.png'